export interface DeviceCategories {
  title: string;
  items: string[];
}

export const DEVICE_CATEGORIES: DeviceCategories[] = [
  {
    title: "Smartphones & Tablets",
    items: [
      "iPhone 15 / 14 / 13 / 12 / 11 / X / SE",
      "iPhone 16-serie en nieuwere iOS-modellen",
      "iPad, iPad Air, iPad Mini & iPad Pro",
      "iOS & iPadOS 13+ IPTV-Apps",
      "Samsung Galaxy S / Z Fold / Z Flip / Note",
      "Google Pixel Smartphones",
      "OnePlus, Xiaomi, Redmi, Poco, Oppo, Realme",
      "Motorola, Nokia, Nothing, Sony Xperia, ASUS ROG",
      "Huawei, Honor & HarmonyOS-apparaten via player-apps",
      "Android-smartphones met Android 7+",
      "Samsung Galaxy Tab",
      "Lenovo Tab, Xiaomi Pad, OnePlus Pad, Oppo Pad",
      "Huawei MatePad & Honor Pad",
      "Amazon Fire HD Tablets",
      "IPTV Smarters, GSE IPTV, XCIPTV, Televizo",
      "TiviMate Companion, OTT Navigator, IPTV Extreme",
    ],
  },
  {
    title: "Smart-tv's & Amsterdam",
    items: [
      "Samsung Smart-tv / Tizen OS (2016+)",
      "Samsung Tizen 2.4, 3.0, 4.0, 5.0, 6.0, 7.0+",
      "LG Smart-tv / WebOS 3.0, 4.0, 5.0, 6.0, 22, 23, 24+",
      "Sony Bravia Google TV & Android TV",
      "Sony Bravia 2015+ Android TV & 2021+ Google TV",
      "Philips Saphi, Android TV & Google TV",
      "Philips Ambilight TV, Android TV, Google TV",
      "Panasonic Smart-tv / My Home Screen",
      "Panasonic Android TV, Fire TV & OLED/LCD-Serien",
      "Hisense VIDAA & Google TV",
      "Hisense VIDAA U3, U4, U5, U6, U7+",
      "TCL Roku TV, Android TV & Google TV",
      "TCL C/P/S-Serien, Roku TV & Google TV",
      "Sharp Android TV, Google TV & Aquos",
      "Toshiba Smart-tv, Fire TV & Android TV",
      "Grundig, JVC, Hitachi, Vestel, Telefunken Smart-tv",
      "Nokia Smart-tv, Xiaomi TV, Metz, Loewe, Blaupunkt",
      "Roku TV, Fire TV Edition & Android TV Edition",
      "Smart-tv met browserondersteuning of M3U/IPTV-app",
      "Smart IPTV, IBO Player, SET IPTV, Net IPTV",
      "SS IPTV, DuplexPlay, Flix IPTV, SmartOne IPTV",
      "Hot IPTV, Smart STB, Bay IPTV, Room IPTV",
    ],
  },
  {
    title: "Computers & Laptops",
    items: [
      "Windows 11 / 10 PCs & Laptops",
      "Windows 8.1 & Windows 7 via VLC/Kodi, indien ondersteund",
      "Microsoft Surface Pro, Laptop & Studio",
      "macOS MacBook, iMac, Mac Mini & Mac Studio",
      "macOS Sonoma, Ventura, Monterey & oudere ondersteunde versies",
      "Linux Ubuntu, Debian, Fedora, Mint",
      "Arch, Manjaro, Pop!_OS, OpenSUSE & Raspberry Pi OS",
      "Chromebook & ChromeOS",
      "All-in-One-PCs, Gaming-Laptops & Workstations",
      "Mini-PC, Intel NUC, Beelink, Geekom",
      "Raspberry Pi 3/4/5 met Kodi, VLC of browser",
      "VLC, Kodi, MyIPTV Player, IPTV Smarters",
      "Webspeler via Chrome, Edge, Firefox, Safari",
    ],
  },
  {
    title: "Amsterdamapparaten",
    items: [
      "Amazon Fire TV Stick (alle Versionen)",
      "Fire TV Stick Lite, 4K, 4K Max & Cube",
      "Google Chromecast 3, Chromecast Ultra",
      "Chromecast met Google TV HD & 4K",
      "Apple TV 4K & HD",
      "Apple TV tvOS 13+ via compatibele IPTV-apps",
      "Roku Express, Premiere, Ultra & Amsterdam Stick",
      "Roku TV & Roku-OS-apparaten met M3U-/browseropties",
      "Xiaomi Mi Box & Stick",
      "Xiaomi TV Stick 4K, Mi Box S 2nd Gen",
      "Nokia Amsterdam Box",
      "Strong Leap, Homatics Box, Mecool, Ugoos",
      "Nvidia Shield TV & Shield TV Pro",
      "Nvidia Shield 2015, 2017, 2019 Tube & Pro",
      "Realme TV Stick, Dynalink, TiVo Stream 4K",
      "Onn Android TV Box, Walmart Google TV Box",
      "Android-tv-box met Android 7+",
      "Amlogic-box S905/S912/S922 met IPTV-speler",
    ],
  },
  {
    title: "Tv-boxen",
    items: [
      "MAG 250, 254, 256, 322, 324, 420, 520",
      "MAG 524, 540, 544, 555 & Ministra-/Stalker-portalen",
      "Formuler Z7, Z8, Z10, Z11, Z Mini, GTV",
      "Formuler Z Alpha, Z Nano, Z10 Pro Max, Z11 Pro Max",
      "BuzzTV XRS, X5, Classic, Vidstick",
      "BuzzTV XR/XR4000/XR4500/X5 AI-Serie",
      "Dreambox DM One, DM Two, DM920",
      "VU+ Zero, Uno, Duo, Solo, Ultimo",
      "Zgemma H9, H11, i55, H7",
      "Amiko, Octagon, Edision, Gigablue",
      "Mutant, Axas, Qviart, Dinobot, Wetek",
      "Enigma2, XtreamTV, Stalker Portal, Ministra",
      "TVIP, Infomir, AuraHD, Openbox",
      "Android-STB met MyTVOnline, Stalker of Xtream Codes",
    ],
  },
  {
    title: "Spelconsoles",
    items: [
      "PlayStation 5 & PlayStation 4",
      "PlayStation 3 via DLNA/browser, indien beschikbaar",
      "Xbox Series X | S",
      "Xbox One & One S/X",
      "Xbox 360 via mediaspeler",
      "Nintendo Switch via browser of capture-setup",
      "Nintendo Wii U via browser, indien beschikbaar",
      "Steam Deck via browser, VLC of Kodi",
      "ROG Ally / Legion Go Windows-Handhelds",
      "AYANEO, MSI Claw & weitere tragbare Windows-Konsolen",
    ],
  },
  {
    title: "Mediaspelers",
    items: [
      "Kodi (op elk apparaat)",
      "VLC Media Player",
      "VLC op Windows, macOS, Linux, Android & iOS",
      "Plex, Jellyfin & Emby",
      "Perfect Player & IPTV Smarters",
      "TiviMate, OTT Navigator, XCIPTV",
      "GSE Smart IPTV, IBO Player, Televizo",
      "ProgTV, Lazy IPTV, IPTV Extreme",
      "Smarters Pro, SmartOne IPTV, Net IPTV",
      "M3U-Playlist, Xtream Codes API, Stalker-Portal",
      "EPG XMLTV, Catch-up & Multiscreen, indien de app dit ondersteunt",
      "M3U8, HLS, TS-Streams & externe Player",
    ],
  },
  {
    title: "Browsers",
    items: [
      "Google Chrome",
      "Chrome Desktop, Android & ChromeOS",
      "Safari",
      "Safari macOS & iOS/iPadOS",
      "Mozilla Firefox",
      "Microsoft Edge",
      "Opera & Brave",
      "Samsung Internet",
      "Android-WebView-Browser",
      "Silk Browser op Fire TV",
      "Tv-browser op LG, Samsung, Philips & Sony",
      "Webspeler op desktop, tablet & mobiel apparaat",
      "Chromium-browser zoals Vivaldi, Arc & Yandex",
      "Browser met HLS/M3U8-ondersteuning",
    ],
  },
];
